# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: sadoming <sadoming@student.42barcel>       +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2023/05/02 16:14:42 by sadoming          #+#    #+#              #
#    Updated: 2023/06/28 17:32:57 by sadoming         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME = libft.a

CFLAGS = -Wall -Wextra -Werror

LIB = libft.h

SRC = ft_atoi.c ft_bzero.c ft_calloc.c ft_isalnum.c ft_isalpha.c ft_isascii.c ft_isdigit.c\
	  ft_isprint.c ft_itoa.c ft_memchr.c ft_memcmp.c ft_memcpy.c ft_memmove.c ft_memset.c\
	  ft_putchar_fd.c ft_putendl_fd.c ft_putnbr_fd.c ft_putstr_fd.c ft_split.c ft_strchr.c\
	  ft_strdup.c ft_striteri.c ft_strjoin.c ft_strlcat.c ft_strlcpy.c ft_strlen.c ft_strmapi.c\
	  ft_strncmp.c ft_strnstr.c ft_strrchr.c ft_strtrim.c ft_substr.c ft_tolower.c ft_toupper.c

BONUS = ft_lstadd_back.c ft_lstclear.c ft_lstdelone.c ft_lstadd_front.c ft_lstiter.c ft_lstlast.c\
	   	ft_lstmap.c ft_lstnew.c ft_lstsize.c

OBJ = $(patsubst %.c, %.o, $(SRC))
OBJB = $(patsubst %.c, %.o, $(BONUS))
# ********************************************* #

all: $(NAME)

%.o : %.c $(LIB)
	cc $(CFLAGS) -c -o $@ $< 

$(NAME): ${OBJ}
	ar rc $(NAME) $(OBJ)

bonus: ${OBJB}
	ar rc $(NAME) $(OBJB)

clean:
	/bin/rm -f *.o

fclean : clean
	/bin/rm -f $(NAME)

re: fclean all

rebonus: fclean bonus

.PHONY: bonus clean fclean re rebonus

# ******************************************* #
